feat(dpav-2563): Build management node image correctly

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -33,6 +33,7 @@ on:
 
 env:
   MAVEN_CLI_OPTS: "--batch-mode --no-transfer-progress"
+  DOCKER_TARGET: management-node
 
 jobs:
   build:
@@ -82,25 +83,52 @@ jobs:
           GH_PACKAGES_PAT: ${{ secrets.GH_PACKAGES_PAT }}
         run: ./mvnw $MAVEN_CLI_OPTS spotless:check
   security-scanning:
-    name: Security Scanning
     runs-on: ubuntu-latest
-    timeout-minutes: 10
+    needs: build
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+      - name: Validate docker target
+        run: |
+          if [[ "${{ env.docker_target }}" != "management-node" ]]; then
+            echo "Docker target is invalid. Use management-node"
+            exit 1
+          fi
+
+      - name: Get version
+        id: get_version
+        run: echo project_version=$(./mvnw $MAVEN_CLI_OPTS help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT
+
+      - name: Checkout repo
+        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
+
+      - name: Login to ghcr.io
+        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Format repo name
+        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
+
+      - name: Get server and client jars
+        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
+        with:
+          pattern: management-node-*.jar
+          path: target
+          merge-multiple: true
 
       - name: Build Server Image
-        run: docker build --no-cache --build-arg JAR_NAME="management-node-${{ inputs.jar_version }}" -t ghcr.io/${REPO}/management-node:staged -f "${{ github.workspace }}/docker/Dockerfile" --target ${{ inputs.docker_target }} .
+        run: docker build --no-cache --build-arg JAR_NAME="management-node-${{ steps.get_version.outputs.project_version}}" -t ghcr.io/${REPO}/management-node:staged -f "${{ github.workspace }}/docker/Dockerfile" --target ${{ env.docker_target }} .
 
       - name: Run Trivy vulnerability scanner
         uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
         with:
           image-ref: ghcr.io/${REPO}/management-node:staged
-          format: "table"
-          exit-code: "1"
+          format: table
+          exit-code: 1
           ignore-unfixed: true
           severity: "CRITICAL,HIGH"
-        continue-on-error: true
+        continue-on-error: false
 
-      - name: Clean up staged image
+      - name: Clean up docker image
         run: docker rmi ghcr.io/${REPO}/management-node:staged
